export const USERINFO_RECEIVED = 'USERINFO_RECEIVED';

export const ABTEST_REQUEST = 'MY_HOTEL/ABTEST_REQUEST';
export const ABTEST_SUCCESS = 'MY_HOTEL/ABTEST_SUCCESS';
export const ABTEST_FAILURE = 'MY_HOTEL/ABTEST_FAILURE';

export const COMMENT_USEFUL_COUNT_REQUEST = 'MY_HOTEL/COMMENT_USEFUL_COUNT_REQUEST';
export const COMMENT_USEFUL_COUNT_SUCCESS = 'MY_HOTEL/COMMENT_USEFUL_COUNT_SUCCESS';
export const COMMENT_USEFUL_COUNT_FAILURE = 'MY_HOTEL/COMMENT_USEFUL_COUNT_FAILURE';

export const GOTO_MY_USEFUL_COMMENT = 'MY_HOTEL/GOTO_MY_USEFUL_COMMENT';

export const COMMENT_USEFUL_LIST_REQUEST = 'MY_HOTEL/COMMENT_USEFUL_LIST_REQUEST';
export const COMMENT_USEFUL_LIST_SUCCESS = 'MY_HOTEL/COMMENT_USEFUL_LIST_SUCCESS';
export const COMMENT_USEFUL_LIST_FAILURE = 'MY_HOTEL/COMMENT_USEFUL_LIST_FAILURE';

export const COMMENT_BRIEF_REQUEST = 'MY_HOTEL/COMMENT_BRIEF_REQUEST';
export const COMMENT_BRIEF_SUCCESS = 'MY_HOTEL/COMMENT_BRIEF_SUCCESS';
export const COMMENT_BRIEF_FAILURE = 'MY_HOTEL/COMMENT_BRIEF_FAILURE';

export const GOTO_COMMENT = 'MY_HOTEL/GOTO_COMMENT';
export const GOTO_MY_ALL_COMMENTS = 'MY_HOTEL/GOTO_MY_ALL_COMMENTS';
export const GOTO_MY_PENDING_COMMENTS = 'MY_HOTEL/GOTO_MY_PENDING_COMMENTS';
export const GOTO_INTEGRAL_RULE = 'MY_HOTEL/GOTO_INTEGRAL_RULE';

export const ASK_BRIEF_REQUEST = 'MY_HOTEL/ASK_BRIEF_REQUEST';
export const ASK_BRIEF_SUCCESS = 'MY_HOTEL/ASK_BRIEF_SUCCESS';
export const ASK_BRIEF_FAILURE = 'MY_HOTEL/ASK_BRIEF_FAILURE';

export const GOTO_ASK = 'MY_HOTEL/GOTO_ASK';
export const GOTO_MY_ALL_ASKS = 'MY_HOTEL/GOTO_MY_ALL_ASKS';
export const GOTO_MY_PENDING_ASKS = 'MY_HOTEL/GOTO_MY_PENDING_ASKS';

export const USER_PIC_STATUS_REQUEST = 'MY_HOTEL/USER_PIC_STATUS_REQUEST';
export const USER_PIC_STATUS_SUCCESS = 'MY_HOTEL/USER_PIC_STATUS_SUCCESS';
export const USER_PIC_STATUS_FAILURE = 'MY_HOTEL/USER_PIC_STATUS_FAILURE';

export const GOTO_MY_PICS = 'MY_HOTEL/GOTO_MY_PICS';

export const MY_FAVORITE_HOTELS_REQUEST = 'MY_HOTEL/MY_FAVORITE_HOTELS_REQUEST';
export const MY_FAVORITE_HOTELS_SUCCESS = 'MY_HOTEL/MY_FAVORITE_HOTELS_SUCCESS';
export const MY_FAVORITE_HOTELS_FAILURE = 'MY_HOTEL/MY_FAVORITE_HOTELS_FAILURE';

export const GOTO_MY_FAVORITE_HOTELS = 'MY_HOTEL/GOTO_MY_FAVORITE_HOTELS';

export const GOTO_MY_BROWSED_HISTORY = 'MY_HOTEL/GOTO_MY_BROWSED_HISTORY';

export const MY_COUPON_REQUEST = 'MY_HOTEL/MY_COUPON_REQUEST';
export const MY_COUPON_SUCCESS = 'MY_HOTEL/MY_COUPON_SUCCESS';
export const MY_COUPON_FAILURE = 'MY_HOTEL/MY_COUPON_FAILURE';

export const GOTO_MY_COUPON = 'MY_HOTEL/GOTO_MY_COUPON';

export const GOTO_MY_CREDIT = 'MY_HOTEL/GOTO_MY_CREDIT';

export const GOTO_MY_REWARDSDETAIL_HOTELS = 'MY_HOTEL/GOTO_MY_REWARDSDETAIL_HOTELS';
export const MY_REWARDS_HOTELS_SUCCESS = 'MY_HOTEL/MY_REWARDS_HOTELS_SUCCESS';
