/**
 * Created by shbzhang on 14/12/29.
 */

var requirejs = {
  "app": {
    "options": {
      "baseUrl"     : "<%= config.TEMP_DIR %>/tempWeb",
      "webSeparator": "lizard.web.beta.src.js",
      //"hybridSeparator": "lizard.hybrid.src.js",
      //"seoSeparator": "v8/parser.src.js",
      "uglify"      : {
        "except": ["$super"]
      },
      "paths"       : {
        "json2" : "3rdlibs/json2",
        "bridge": "3rdlibs/bridge",
        "R"     : "3rdlibs/require",
        "$"     : "3rdlibs/zepto",
        "_"     : "3rdlibs/underscore",
        "B"     : "3rdlibs/backbone",
        "F"     : "3rdlibs/fastclick",
        "libs"  : "3rdlibs/libs",
        "text"  : "3rdlibs/require.text",

        "cCoreInherit": "common/c.class.inherit",

        "cMessageCenter": "common/c.message.center",
        "cAjax"              : "common/c.ajax",
        "cImgLazyload"       : "common/c.img.lazyload",
        "cPageParser"        : "app/c.page.parser",
        "cPageModelProcessor": "app/c.page.model.processor",
        "cParserUtil"        : "app/c.parser.util",
        "cPageView"          : "page/c.page.view",
        "cPageList"          : "page/c.page.list",

        "cUtilCacheView": "util/c.util.cacheview",
        "cUtilCommon": "util/c.util.common",
        "cUtilDate"  : "util/c.util.date",

        "cUtilHybrid": "util/c.util.hybrid",
        "cUtilObject"     : "util/c.util.object",
        "cUtilPath"       : "util/c.util.path",
        "cUtilPerformance": "util/c.util.performance",
        "cUtilValidate"   : "util/c.util.validate",
        "cUtilCryptBase64": "util/crypt/c.crypt.base64",
        "cUtilCryptRSA"   : "util/crypt/c.crypt.rsa",

        "cAbstractStore": "data/store/c.abstract.store",
        "cLocalStore"      : "data/store/c.local.store",
        "cSessionStore"    : "data/store/c.session.store",
        "cMemoryStore"     : "data/store/c.memory.store",
        "cCommonStore"     : "data/store/c.common.store",
        "cHeadStore"       : "data/store/common/c.head.store",
        "cAuthStore"       : "data/store/common/c.auth.store",
        "cUserStore"       : "data/store/common/c.user.store",
        "cMarketStore"     : "data/store/common/c.market.store",
        "cMobileTokenStore": "data/store/common/c.mobiletoken.store",

        "cAbstractModel": "data/model/c.abstract.model",
        "cModel"    : "data/model/c.model",
        "cUserModel": "data/model/c.user.model",

        "cAbstractStorage": "data/storage/c.abstract.storage",
        "cLocalStorage"  : "data/storage/c.local.storage",
        "cSessionStorage": "data/storage/c.session.storage",
        "cMemoryStorage" : "data/storage/c.memory.storage",
        "cCookieStorage"  : "data/storage/c.cookie.storage",

        "cUIBase": "ui_beta/c.ui.base",
        "UIView"        : "ui_beta/ui.abstract.view",
        "UILayer"       : "ui_beta/ui.layer",
        "UIAlert"       : "ui_beta/ui.alert",
        "UIMask"        : "ui_beta/ui.mask",
        "UILoading"     : "ui_beta/ui.loading",
        "UILoadingLayer": "ui_beta/ui.loading.layer",
        "UIToast"       : "ui_beta/ui.toast",
        "UIInlineView"  : "ui_beta/ui.inline.view",
        "UINum"         : "ui_beta/ui.num",
        "UISwitch"      : "ui_beta/ui.switch",
        "UIBubbleLayer" : "ui_beta/ui.bubble.layer",
        "UITab"         : "ui_beta/ui.tab",
        "UIScroll"      : "ui_beta/ui.scroll",
        "UIScrollLayer" : "ui_beta/ui.scroll.layer",
        "UIRadioList"   : "ui_beta/ui.radio.list",
        "UISelect"      : "ui_beta/ui.select",
        "UIGroupSelect" : "ui_beta/ui.group.select",
        "UIGroupList"   : "ui_beta/ui.group.list",
        "UICalendar"    : "ui_beta/ui.calendar",
        "UISlider"      : "ui_beta/ui.slider",
        "UIImageSlider" : "ui_beta/ui.image.slider",
        "cUIInputClear" : "ui_beta/c.ui.input.clear",
        "UIWarning404"  : "ui_beta/ui.warning404",
        "UITemplates"   : "ui_beta/ui.templates",
        "UIHeader"      : "ui_beta/ui.header",
        "UILoading"     : "http://1",
        "UIIdentitycard": "ui_beta/ui.identitycard",
        "UILayerList"       : "ui_beta/ui.layer.list",
        "UIAnimation"       : "ui_beta/c.ui.animation",
        "cGeoService"       : "service/c.service.geo",
        "cMemberService"    : "service/c.service.member",
        "cGuiderService"    : "service/c.service.guider",
        "cHybridMember"     : "service/hybrid/c.hybrid.memberService",
        "cHybridGuider"     : "service/hybrid/c.hybrid.guider",
        "cHybridGeolocation": "service/hybrid/c.hybrid.geolocation",
        "cGeoHelper"        : "service/web/c.geo.helper",
        "cGeoLocation"      : "service/c.geo.location",
        "cWebMember"        : "service/web/c.web.memberService",
        "cWebGuider"        : "service/web/c.web.guider",
        "cWebGeolocation"   : "service/web/c.web.geolocation",
        "cBMap"           : "service/web/map/c.web.geolocation.bmap",
        "cGMap"           : "service/web//map/c.web.geolocation.gmap",
        "cStatic": "app/web/c.web.static",
        "cHybridApp"    : "app/hybrid/c.hybrid.app",
        "cBaseInit"     : "app/c.base.init",
        "cAbstractApp"  : "app/c.abstract.app",
        "cHybridFacade" : "app/hybrid/c.hybrid.facade",
        "cHybridShell"  : "app/hybrid/c.hybrid.shell",
        "config"        : "config",
        "seed"          : "lizard.seed",
        "cHybridAppInit": "app/hybrid/c.hybrid.init",
        "cWebAppInit"   : "app/web/c.web.init",
        "cWebApp"       : "app/web/c.web.app",
        "cPadExtend":     "app/c.pad.extend",
        "cPadApp":        "app/web/c.pad.app",
        "cWebViewApp"   : "app/hybrid/c.webview.app",
        "cHybridHeader" : "app/hybrid/c.hybrid.header",
        "cHybridStart"  : "app/hybrid/c.hybrid.start",

        "almond": "v8/almond",
        "seoUnderscore" : "v8/underscore_v8",
        "seoHtmlParser" : "v8/htmlParse_v8",
        "seoVm"         : "v8/vm_v8",
        "cSeoEntendUtil": "v8/c.seo.extendutils",
        "cSeoUrlmapping": "v8/c.seo.urlmapping",
        "cSeoGetModels" : "v8/c.seo.getmodels",
        "cSeoRender"    : "v8/c.seo.render",
        "cSeoMain"      : "v8/c.seo.main",

        "cPlugins": "plugins/c.plugins",
        "cJsonPlugin"      : "plugins/c.json.plugin",
        "cMarketPlugin"    : "plugins/c.market.plugin",
        "cSafariPlugin"    : "plugins/c.safari.plugin",
        "cStatisticsPlugin": "plugins/c.statistics.plugin",
        "cZeptoPlugin"     : "plugins/c.zepto.plugin",
        "cUnderscorePlugin": "plugins/c.underscore.plugin",
        "cShell"           : "shell/c.shell",

        "loading"          : "http://webresource.c-ctrip.com/ResCRMOnline/R5/basewidget/ui.load",
        "loadFailed"       : "http://webresource.c-ctrip.com/ResCRMOnline/R5/basewidget/ui.loadFailed"
      },
      "include"     : [
        "R",
        "$",
        "_",
        "B",
        "F",
        "libs",
        "text",
        "seed",
        "config",
        "cCoreInherit",
        "cMessageCenter",
        "cAjax",
        "cImgLazyload",
        "cPageParser",
        "cParserUtil",
        "cUtilCacheView",
        "cUtilCommon",
        "cUtilDate",
        "cUtilPath",
        "cUtilObject",
        "cUtilPerformance",
        "cUtilValidate",
        "cUtilCryptBase64",
        "cUtilHybrid",
        "cAbstractStore",
        "cAbstractStorage",
        "cLocalStore",
        "cLocalStorage",
        "cSessionStore",
        "cSessionStorage",
        "cCookieStorage",
        "cMemoryStore",
        "cCommonStore",
        "cJsonPlugin",
        "cMarketPlugin",
        "cSafariPlugin",
        "cStatisticsPlugin",
        "cUnderscorePlugin",
        "cZeptoPlugin",
        "cPlugins",
        "cAbstractModel",
        "cModel",
        "cUserModel",
        "cPageView",
        "cPageList",
        "cGeoService",
        "cMemberService",
        "cGuiderService",
        "cGeoHelper",
        "cGeoLocation",
        "cStatic",
        "cBaseInit",
        "cAbstractApp",
        "UIWarning404",
        "UILoadingLayer",
        "cWebApp",
        "cPadExtend",
        "cShell",
        "webSeparator",
        "cWebAppInit",
        "UIHeader",
        "cWebMember",
        "cWebGuider",
        "cWebGeolocation",
        "text!ui/ui.loading.layer.html",
        "text!ui/ui.mask.html",
        "text!ui/ui.warning404.html",
        "text!ui/ui.alert.html",
        "text!ui/ui.toast.html",
        "text!ui/ui.header.html",
        "text!ui/ui.bubble.layer.html"
      ],
      "out"         : "<%= config.WEB_TEMP_DIR %>/lizard.seed.beta.src.js"
    }
  }
}
